version: '3.8'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - redis_net
            - db_net
        environment:
            - SECRET_KEY=tk2epcbmwfbl@h7mj(wa+_q!q*r=p)%xor5a!n0j&t$$%xkr29g
            - DEBUG=1
            - ENVIRONMENT=development
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            PGDATA: /var/lib/postgresql/data/test_chat/
        networks:
            - db_net

    redis:
        image: redis:5
        container_name: redis_db
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        restart: always
        networks:
            - redis_net


volumes:
    postgres_data:

networks:
  redis_net:
    driver: bridge
  db_net:
    driver: bridge
